### ISSUE TITLE
Linter seems to not pick up .zip release 

### ISSUE THREAD

**Issue by eliasblume** [hlaueriksson/Community.PowerToys.Run.Plugin.Lint#1]
Hello, I tried to use your linter for my project https://github.com/eliasblume/powertoys-run-jetbrains-projects here.
I think the release is in OK format but somehow your linter doesn't pick it up, any ideas ?
![image](https://github.com/user-attachments/assets/7cb325a3-3877-4820-8851-9e1c1403d1a8)

when i run ` ptrun-lint https://github.com/eliasblume/powertoys-run-jetbrains-projects` i get 
```
PTRUN1201: Release should be valid
 - Asset ".zip" missing
 ```

![image](https://github.com/user-attachments/assets/587ccad6-033c-4acc-905c-eedd2d821b1b)

**Comment by hlaueriksson** [comment]
The regex for picking up the packages is a bit too strict: https://github.com/hlaueriksson/Community.PowerToys.Run.Plugin.Lint/blob/1ccd14a537bba4f5ab50bca2c7383a684db46de7/src/Community.PowerToys.Run.Plugin.Lint/Rules.cs#L195

If you remove the `v` prefix in the version, it works:

```
JetbrainsProjects-1.0.2-x64.zip
JetbrainsProjects-1.0.2-arm64.zip
```

**Comment by hlaueriksson** [comment]
If you want to fix the regex and create a PR, you are welcome.

**Comment by eliasblume** [comment]
![image](https://github.com/user-attachments/assets/c7e6b597-dc37-4099-b7da-41302c055dc5)
I changed the names, though the error remained - so idk if its a caching issue or smth 
![image](https://github.com/user-attachments/assets/c242bd74-5352-410b-9b01-e6467c8e112a)

could i be that i upload the ZIPs after initial release ?

**Comment by hlaueriksson** [comment]
It seems like your packages has the content type `binary/octet-stream`:

- https://api.github.com/repos/eliasblume/powertoys-run-jetbrains-projects/releases/latest

The linter are looking for something with `zip`, for example `application/zip`.
I wonder how the `content_type` is decided.

**Comment by eliasblume** [comment]
When I download the archive, it works fine - I suspect the action is a bit to blame.
Once I download and re-upload the ZIPs, it seems to work fine so probably I need to look into my action
![image](https://github.com/user-attachments/assets/53f3ee37-0f8a-47cb-b8e9-d17980e30d8f)

(this issue truly is my messed-up `plugin.json`)

**Comment by hlaueriksson** [comment]
The hash errors are a bit of nit picking.

I put the SHA256 hashes in the release notes:

- https://github.com/hlaueriksson/GEmojiSharp/releases/tag/v4.0.1

They are generated with a script:

- https://github.com/hlaueriksson/GEmojiSharp/blob/master/src/GEmojiSharp.PowerToysRun/release.ps1

**Comment by eliasblume** [comment]
@hlaueriksson i finally had the time to fix it - works great now, thx for the help :) 

updating [the action](https://github.com/eliasblume/powertoys-run-jetbrains-projects/blob/master/.github/workflows/build.yml) to specify a mime and reusing [ur script](https://github.com/eliasblume/powertoys-run-jetbrains-projects/blob/master/Community.PowerToys.Run.Plugin.JetbrainsProjects/create-release-notes.ps1) worked well

**Comment by hlaueriksson** [comment]
For the next release I have a few things on my TODO list. For example:

- Also look for packages with extension `.zip`
- Lax the regex to match `v` prefix of version in the filename
