### ISSUE TITLE
How to pass PTRUN1501 (Target platform should be "windows")

### ISSUE THREAD

**Issue by neilenns** [hlaueriksson/Community.PowerToys.Run.Plugin.Lint#2]
What do I modify in my project to get this rule to pass?

I generated my plugin using https://github.com/hlaueriksson/Community.PowerToys.Run.Plugin.Templates. I can't find any examples among the published plugins that specify a `TargetPlatformAttribute` in the .csproj file and yet some plugins (e.g. `PowerToys-Run-InputTyper`) seem to pass this rule.

Thanks!

**Comment by neilenns** [comment]
I think I figured this out. My `TargetFramework` was set to `net8.0-windows10.0.22621.0`. I found another plugin that passed this test, and it used `net8.0-windows` instead. Changing that made the test pass.

**Comment by hlaueriksson** [comment]
The target framework `net8.0-windows10.0.22621.0` is actually correct.

The linter rule is old:
https://github.com/hlaueriksson/Community.PowerToys.Run.Plugin.Lint/blob/1ccd14a537bba4f5ab50bca2c7383a684db46de7/src/Community.PowerToys.Run.Plugin.Lint/Rules.cs#L327

In the next release it should be: `net9.0-windows10.0.22621.0`

- https://github.com/microsoft/PowerToys/blob/c5dc93f72071b13e4d5917b73bc693484b2e6b1e/src/Common.Dotnet.CsWinRT.props#L6

**Comment by hlaueriksson** [comment]
This will be fixed in the next release

**Comment by neilenns** [comment]
For what it's worth, I tried rolling my plugin to `net9.0-windows10.0.22621.0` and it fails to load because I guess I don't have the right runtime installed on my computer. I'll be sticking with net8.0 for now :)

**Comment by hlaueriksson** [comment]
I think `0.87` of PowerToys will be released next week. With that `<TargetFramework>net9.0-windows10.0.22621.0</TargetFramework>` can be used.

I will update and release a new version of the linter then.

**Comment by hlaueriksson** [comment]
This is now fixed in [0.3.0](https://www.nuget.org/packages/Community.PowerToys.Run.Plugin.Lint/0.3.0)
