### ISSUE TITLE
Support a checksums.txt file for passing the checksums test

### ISSUE THREAD

**Issue by neilenns** [hlaueriksson/Community.PowerToys.Run.Plugin.Lint#4]
My plugin release process is fully automated via GitHub workflows. I make a GitHub release and the action gets packed and uploaded as an asset, along with auto-generated release notes.

The only linting test I can't pass with this is the requirement to have checksums in the release notes. This would require me to manually edit the release notes on every release, defeating the purpose of having automatically generated releases.

Can you consider supporting a checksums.txt file on the release as the source for the checksum information? This is easily added to the release via a workflow (see https://github.com/neilenns/DiscordTimestamp/releases/tag/v1.0.3 for an example). If the linter looked at this, instead of (or in addition to) the release notes then I could pass this test without any human intervention.

**Comment by hlaueriksson** [comment]
Yes, this is a good idea!

**Comment by hlaueriksson** [comment]
@neilenns Do you want to review #10?

**Comment by hlaueriksson** [comment]
This is now implemented in [0.3.0](https://www.nuget.org/packages/Community.PowerToys.Run.Plugin.Lint/0.3.0)
